status/urls.py
from django.urls import path

from . import views

app_name = 'status'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('confirmation/add', views.add_status, name='add_status'),
    path('color/<str:pk>', views.change_color, name='change_color')
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("status.urls"))
]

status/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length=50)
    status = models.TextField(max_length=500)
    color = models.CharField(max_length=20, default='#fbfbfb')
    def __str__(self):
        return self.name

status/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name', 'status']
        widgets = {
            'name' : forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Your Name"}),
            'status' : forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Wanna share something?',
                'rows':'4'
            })
        }

status/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import StatusForm
from .models import Status

# Create your views here.

def index(request):
    status = Status.objects.all();
    form = StatusForm()
    context = {
        'status': status,
        'form': form
    }
    return render(request, "status/index.html", context)

def confirmation(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        context = {
            'form': form,
            'name': request.POST['name'],
            'status': request.POST['status']
        }       
        return render(request, "status/confirmation.html", context)
    else:
        return redirect('status:index')

def add_status(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('status:index')
    else:
        return redirect('status:index')

def change_color(request,pk):
    colorList = ['#fbfbfb', '#fff1c1', '#f4f3f3', '#78b7bb', '#808b97']
    status = Status.objects.get(id=pk)
    colorIndex = (colorList.index(status.color) + 1) % 5 + 1
    newColor = colorList[colorIndex-1]
    status.color = newColor
    status.save()
    return redirect('status:index')

status/templates/status/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    
    {% endblock css %}
    <title>People Stories</title>
</head>
<body>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

status/templates/status/confirmation.html
{% extends 'status/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'status/style.css' %}">
{% endblock css %}
{% block content %}
<nav class="navbar navbar-light bg-light px-5">
    <a class="navbar-brand" href="{% url 'status:index' %}">
        <img src="{% static 'status/images/chat.svg' %}" width="30" height="30" class="d-inline-block align-top mr-2"
            alt="">
        People Story
    </a>
</nav>
<div class="d-flex flex-column pt-5 align-items-center container wrapper">
    <div class="col-md-8">

        <form action=" {% url 'status:add_status' %}" method="POST">
        {% csrf_token %}
        <div class="d-none">
            {{ form }}
        </div>
        <div class="card">
            <div class="card-header">
              Confirmation
            </div>
            <div class="card-body">
              <h5 class="card-title">Hi, {{ name }}</h5>
              <p class="card-text">Are you sure to post this status?</p>
              <h4 class="text-info text-center my-3"><span>&#x201c</span> {{ status }} <span>&#x201d</span></h4>
              <div class="d-flex justify-content-end">
                <a href="{% url 'status:index' %}" class="btn btn-secondary mr-2">No</a>
                <button class="btn btn-success mr-2" type="submit">Yes</button>
              </div>
            </div>
          </div>
        </form>
    </div>
</div>

{% endblock content %}

status/templates/status/index.html
{% extends 'status/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'status/style.css' %}">
{% endblock css %}
{% block content %}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="{% url 'status:confirmation' %}" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <label>Name:</label>
                    {{ form.name }}
                    <label>Status:</label>
                    {{ form.status }}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
<nav class="navbar navbar-light bg-light px-5">
    <a class="navbar-brand" href="{% url 'status:index' %}">
        <img src="{% static 'status/images/chat.svg' %}" width="30" height="30" class="d-inline-block align-top mr-2"
            alt="">
        People Story
    </a>
    <button class="btn btn-outline-success my-2 my-sm-0" data-toggle="modal" data-target="#exampleModal">Add
        Story</button>
</nav>

<div class="d-flex flex-column {% if status|length == 0 %} justify-content-center {% else %} justify-content-start pt-5 {% endif %} align-items-center container wrapper pb-5">
    {% if status|length == 0 %}
    <div class="nodata d-flex flex-column align-items-center">
        <img src="{% static 'status/images/speech.svg' %}" width="60" height="60">
        <h2 class="mt-3">Be The First to share story here</h2>    
    </div>
    {% else %}
    {% for item in status %}
    <div class="col-md-9 border rounded-lg p-4 m-1" style="background-color: {{ item.color }};">
        <h3>{{ item.name }}</h3>
        <hr>
        <p>{{ item.status }}</p> 
        <a class="btn btn-info" href="{% url 'status:change_color' item.id %}">Change Color</a> 
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock content %}